#! /bin/bash

### BEGIN INIT INFO
# Provides:          RtspVideoStreamRecorder
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RtspVideoStreamRecorder service
# Description:       Run RtspVideoStreamRecorder service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting RtspVideoStreamRecorder..."
    /root/RVSR/start-rvsr.sh&
    ;;
  stop)
    echo "Stopping RtspVideoStreamRecorder..."
    pkill RtspVideoStream
    ;;
  *)
    echo "Usage: /etc/init.d/portreader {start|stop}"
    exit 1
    ;;
esac

exit 0
